linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    # Add more linters as needed (e.g., gosec, unused, deadcode)

run:
  timeout: 5m
  issues-exit-code: 1