// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// SubscriptionId applies equality check predicate on the "subscriptionId" field. It's identical to SubscriptionIdEQ.
func SubscriptionId(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldSubscriptionId, v))
}

// UserId applies equality check predicate on the "userId" field. It's identical to UserIdEQ.
func UserId(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUserId, v))
}

// SubscriptionIdEQ applies the EQ predicate on the "subscriptionId" field.
func SubscriptionIdEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldSubscriptionId, v))
}

// SubscriptionIdNEQ applies the NEQ predicate on the "subscriptionId" field.
func SubscriptionIdNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldSubscriptionId, v))
}

// SubscriptionIdIn applies the In predicate on the "subscriptionId" field.
func SubscriptionIdIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldSubscriptionId, vs...))
}

// SubscriptionIdNotIn applies the NotIn predicate on the "subscriptionId" field.
func SubscriptionIdNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldSubscriptionId, vs...))
}

// SubscriptionIdGT applies the GT predicate on the "subscriptionId" field.
func SubscriptionIdGT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldSubscriptionId, v))
}

// SubscriptionIdGTE applies the GTE predicate on the "subscriptionId" field.
func SubscriptionIdGTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldSubscriptionId, v))
}

// SubscriptionIdLT applies the LT predicate on the "subscriptionId" field.
func SubscriptionIdLT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldSubscriptionId, v))
}

// SubscriptionIdLTE applies the LTE predicate on the "subscriptionId" field.
func SubscriptionIdLTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldSubscriptionId, v))
}

// UserIdEQ applies the EQ predicate on the "userId" field.
func UserIdEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "userId" field.
func UserIdNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "userId" field.
func UserIdIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "userId" field.
func UserIdNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUserId, vs...))
}

// UserIdGT applies the GT predicate on the "userId" field.
func UserIdGT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUserId, v))
}

// UserIdGTE applies the GTE predicate on the "userId" field.
func UserIdGTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUserId, v))
}

// UserIdLT applies the LT predicate on the "userId" field.
func UserIdLT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUserId, v))
}

// UserIdLTE applies the LTE predicate on the "userId" field.
func UserIdLTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUserId, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
