// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/predicate"
	"backend/ent/subscription"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscriptionId sets the "subscriptionId" field.
func (_u *SubscriptionUpdate) SetSubscriptionId(v int) *SubscriptionUpdate {
	_u.mutation.ResetSubscriptionId()
	_u.mutation.SetSubscriptionId(v)
	return _u
}

// SetNillableSubscriptionId sets the "subscriptionId" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableSubscriptionId(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetSubscriptionId(*v)
	}
	return _u
}

// AddSubscriptionId adds value to the "subscriptionId" field.
func (_u *SubscriptionUpdate) AddSubscriptionId(v int) *SubscriptionUpdate {
	_u.mutation.AddSubscriptionId(v)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *SubscriptionUpdate) SetUserId(v int) *SubscriptionUpdate {
	_u.mutation.ResetUserId()
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableUserId(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// AddUserId adds value to the "userId" field.
func (_u *SubscriptionUpdate) AddUserId(v int) *SubscriptionUpdate {
	_u.mutation.AddUserId(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SubscriptionUpdate) SetUserID(id int) *SubscriptionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableUserID(id *int) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionUpdate) SetUser(v *User) *SubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionUpdate) ClearUser() *SubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscriptionId(); ok {
		_spec.SetField(subscription.FieldSubscriptionId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionId(); ok {
		_spec.AddField(subscription.FieldSubscriptionId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserId(); ok {
		_spec.SetField(subscription.FieldUserId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserId(); ok {
		_spec.AddField(subscription.FieldUserId, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetSubscriptionId sets the "subscriptionId" field.
func (_u *SubscriptionUpdateOne) SetSubscriptionId(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetSubscriptionId()
	_u.mutation.SetSubscriptionId(v)
	return _u
}

// SetNillableSubscriptionId sets the "subscriptionId" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableSubscriptionId(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetSubscriptionId(*v)
	}
	return _u
}

// AddSubscriptionId adds value to the "subscriptionId" field.
func (_u *SubscriptionUpdateOne) AddSubscriptionId(v int) *SubscriptionUpdateOne {
	_u.mutation.AddSubscriptionId(v)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *SubscriptionUpdateOne) SetUserId(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetUserId()
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableUserId(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// AddUserId adds value to the "userId" field.
func (_u *SubscriptionUpdateOne) AddUserId(v int) *SubscriptionUpdateOne {
	_u.mutation.AddUserId(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SubscriptionUpdateOne) SetUserID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableUserID(id *int) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionUpdateOne) SetUser(v *User) *SubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionUpdateOne) ClearUser() *SubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscriptionId(); ok {
		_spec.SetField(subscription.FieldSubscriptionId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionId(); ok {
		_spec.AddField(subscription.FieldSubscriptionId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserId(); ok {
		_spec.SetField(subscription.FieldUserId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserId(); ok {
		_spec.AddField(subscription.FieldUserId, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
